### PR TITLE
Package file resolution is failing in windows

### PR DESCRIPTION
**Pull request by dvoaviarison**

### CODE REVIEW

**Comment by mgol** [comment]
I'm surprised it's failing, core NodeJS APIs are supposed to map `/` to `\` on Windows. How is it failing for you?

If it's indeed failing, a correct solution is to use `path.join` and not just switch to the Windows way.

**Comment by mgol** [comment]
Ping

**Comment by dvoaviarison** [comment]
Hey Michael

https://github.com/dvoaviarison/npm-bump/commit/6b876d90f48d4396c5bf4392ded160fac79c71f8

I just wrote some comments here.

Thanks,
-Daniel

On Tue, Feb 7, 2017 at 1:07 AM, Michał Gołębiowski <notifications@github.com

**Comment by mgol** [comment]
@dvoaviarison are you still interested in finalizing this PR?

**Comment by mgol** [comment]
Resolved by 3cf04e1.

**Pull request closed without merging**
